version: "3.3"
services:
  db:
    # build: ./docker/mysql # Location of Dockerfile
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql # レコード置き場
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d # 起動時に実行する
      - ./docker/mysql/conf.d:/etc/mysql/conf.d # 設定ファイル
      - ./log/mysql:/var/log/mysql # ログ置き場
